### ISSUE TITLE
what would be the handler name when we use this zip in aws lambda ?

### ISSUE THREAD

**Issue by vrajroutu** [gshackles/alexa-datadog-sample#2]
<img width="1283" alt="screen shot 2018-07-24 at 12 37 16 am" src="https://user-images.githubusercontent.com/22155528/43117267-edea1baa-8ed9-11e8-8326-1eb2de5a9894.png">

**Comment by gshackles** [comment]
This sample was created using the Serverless framework (though now an admittedly old version, as it's been quite some time since I put this together 😄), so [the handler is defined here in its config](https://github.com/gshackles/alexa-datadog-sample/blob/master/serverless.yml#L12). Hope that helps!
